# Add application configuration variables here, as shown below.

TWITTER_KEY: lgcFBWWUyorIkVOKj82ZQ
TWITTER_SECRET: kl51a7aWvuzRLbMwHaojYoChmgv6sneNNvnqcRPuk

SOUNDCLOUD_KEY: 4c635e586de4923a46e73c2e88ae527c
SOUNDCLOUD_SECRET: fb636886db152edae5444fe197e1a3ac