# Add application configuration variables here, as shown below.

TWITTER_KEY: lgcFBWWUyorIkVOKj82ZQ
TWITTER_SECRET: kl51a7aWvuzRLbMwHaojYoChmgv6sneNNvnqcRPuk
FACEBOOK_KEY: 159840320882958
FACEBOOK_SECRET: b573c4dd91bb4f60b8cee0efd0789151